### ISSUE TITLE
cellArea parameter

### ISSUE THREAD

**Issue by jeffreyhanson** [dimitri-justeau/restoptr#10] opened 2021-12-12 07:41 UTC
Just an idea, could the `cellArea` parameter be automatically derived using the `existing_habitat` data? E.g., we could use  something like `prod(terra::res(existing_habitat))` to compute cell area in m^2?

**Comment by dimitri-justeau** [comment] 2021-12-20 03:39
This is a great idea. Even more, what would be absolutely perfect would be an automatic data preprocessing module, to be sure that the `cellArea` value is consistent with values of the `restorable_habitat` raster values.

For example, the user would only have to give a binary habitat raster as input. If the resolution of this raster is too high for the solver, a resampled binary `existing_habitat` raster along with a `restorable_habitat` raster are produced internally for the solving process.

I think that would be the best option for users. However, I'd like to set it as a `next` target, i.e. first we aim to have a neat package that reproduces more or less the current behaviour of restopt. Once we have that we prepare this feature for the next version. What do you think?

**Comment by jeffreyhanson** [comment] 2021-12-20 20:53
Awesome! Yeah, I really like the idea of helping users avoid issues with inputting data that are too high resolution for the solver. I'm guessing that the total number of cells in the rasters is one limiting factor, are there are other things that should be considered too (e.g. number of distinct components in the raster, numerical precision issues)? How reliably could you estimate the minimum aggregation factor (e.g. see https://rspatial.github.io/terra/reference/aggregate.html) to aggregate rasters layers on a given computer? Some R packages have functions to access the total RAM on a computer - so that might help. 

Also, can rJava use swap space exceed RAM limitations? I know that R can. If so, it might be worth thinking about some way that advanced users can disable the automatic aggregation if they don't mind relying on swap space for really large problems (even if it means waiting a long time given the limitations of swap space).

Perhaps one idea could involve adding an extra parameter to `add_settings()` so that users can specify if they want to enable/disable the automatic raster aggregation? Another idea could involve outputting a warning to provide a recommended aggregation factor that users could run themselves? Yeah, I agree this is something that would be great to explore in the next version.

**Comment by jeffreyhanson** [comment] 2022-02-02 22:10
Just to confirm, my understanding is that -- for the initial release -- the cell area parameter will be automatically computed based on the raster data. Is that right? If so, I'll submit a PR with that functionality.

**Comment by dimitri-justeau** [comment] 2022-03-21 09:32
Hi Jeff ! Sorry that I did not answer sooner. Finally, I implemented functions to automatically aggregate an input binary habitat raster, produce the restorable habitat, and compute the cell areas. It's much better as it prevents many possible errors in preprocessing the data. It also allows to quickly test different resolutions for a given problem. I added the possibility to choose the unit for the parameters of the restorable constraints, and I added an S4 class inheriting from SpatRaster, the RestoptSolution, which embeds the metadata and offers a method for retrieving the solution characteristics with different area units. All of this is in the data_preprocess branch (https://github.com/dimitri-justeau/restoptr/tree/data_preprocess). I modified the documentation, example, etc. It just remains to modify the readme. When you have time to have a look give me your feedback before I can merge this branch to the master.

**Comment by dimitri-justeau** [comment] 2022-03-22 11:35
I updated the README in https://github.com/dimitri-justeau/restoptr/tree/data_preprocess with explanations / instructions about the aggregation factor and the habitat threshold parameter for data preprocessing :-)

**Comment by jeffreyhanson** [comment] 2022-03-22 22:56
Hey - no worries at all!

I'm sorry for my slow response - I'm still swamped. That's really awesome! Wow - the README looks brilliant - nice work! That all sounds great, I just have a few comments/suggestions/questions? if that's ok?

1. Yeah, I like the idea of having a `RestoptSolution` class to store results. I think it's a good way to systematically organize the solution, accompanying metadata, and underying problem. May I ask what the advantage of implementing this class as an S4 class is? I find that S4 classes/methods can be very useful if you need internal data/logic validation, or dispatch on multiple arguments - but I don't see that here? Maybe I'm missing something? Would be simpler to implement this as an S3 class (similar to the `RestoptProblem` class)?
2. I like the idea of allowing users to specify different units - that's really cool. Have you considered using the `units` R package for this? This provides an API for easily converting between different units without needing to manually hard-code all the scaling values (e.g. as in `cell_area()`). E.g., we can convert 5 ha to km^2 using this code:
    ```
    library(units)
    v <- set_units(5, ha)
    set_units(v, km^2)
    ```
    If you want to convert the results back into just numbers, you can do `as.numeric(set_units(v, km^2))`? Or, you could keep 
   the numbers in a unit-aware format in the output? This might also let you provide a wider range of units too?
3. The README shows the user how to access the underlying data in the problem object (e.g. `p$data$habitat_original`). Is this something we want to actively encourage users to do? E.g., future versions of the package might change, and these changes might alter how the data are stored internally - even though the overall results might be the same across different versions? If so, maybe it would be useful to provide a getter function for accessing the aggregated data, and then showing users how that can be used? This way if there are any changes to the internal structure data/organization of the problem object, the users will have a stable API/function for accessing the data across versions? How does that sound?
4. Is it worth mentioning which resampling method is used when the aggregation factor is > 1? E.g., even if this just means specifying that the default resampling method per `terra::aggregate()` is used?
5. I suggest using back-ticks for base R classes in documentation (e.g. `numeric` or `integer`) so it's clear you're reffering to a specific class. E.g., [here](https://github.com/dimitri-justeau/restoptr/blob/data_preprocess/R/restopt_problem.R#L44)  you could maybe use "`numeric` value ..." (or "A `numeric` value ...") instead "Numeric between ..."?
6. The new print method for the `RestoptProblem` class looks incredible!!!

That's everything I can think of - what do you think? Please if there's something else you wanted me to specifically look at?

**Comment by dimitri-justeau** [comment] 2022-03-24 10:33
Hi Jeff, thank you for your feedback :-)

1. I used an S4 class because I wanted the result to be a `terra::rast` (which is an S4 class) with a few supplementary methods. I thought that I can be convenient for users to be able to seamlessly plot manipulate the result. It is true that using an S3 class would be more consistent with the rest of the project, so one solution could be to have an S3 class with the `terra::rast` as an attribute, and eventually override the plot method such that the plotting is dispatched to the underlying raster. However, we would lose the possibility to manipulate the result like any other `terra::rast` (I mean other methods than plot) without an extra `get_rast()` step. We just need to choose an option, I think both have their pro and cons, but maybe for consistency we could go for an S3 class. Do you have any preference ?

2. Thank you for the suggestion, that's a great idea ! I will have a look at the `units` package.

3. You are totally right, implementing getters to retrieve problems' data is much durable option.

4. Yes, I will add more details on the aggregation method. It is not the default one. It corresponds to the ratio between the sum of habitat cells, and the number of non-NA cells, thus the proportion of habitat cells. The habitat threshold parameter defines the minimum proportion needed to consider an aggregated pixel as habitat.

5. You are right, I will modify this !

6. Thank you ! I tried to render the colors in the generated md file, but it does not seem to work on Github.

To answer your last question, nothing in particular, you already provided many improvement advice ! I it is ok for you I will merge this branch to the master branch, and implement the suggestions. Maybe we could also plan a Skype in the next weeks, as I think we are getting close to the first release ?

**Comment by jeffreyhanson** [comment] 2022-03-27 20:17
Awesome thanks! 

Regarding 1: Ah yes - of course! This way we can use all the existing SpatRaster methods in terra, and also add additional slots/methods for the metadata and problems - I think it's the perfect solution! I'm sorry, I mistakenly thought it was a new class entirely. 

Brilliant, yeah, please merge the branch when you think it's ready. Yeah - a meeting to coordinate the release sounds great - let's follow up about this over email.

**Comment by dimitri-justeau** [comment] 2022-03-28 00:41
Thanks, let's stay with the solution being an extension of a SpatRaster then :-)

Nice, I just merged the branch to the master, and addressed all the points we discussed (using the `units` package, back-ticks for parameter and return types, implementing getters, and giving more details about the aggregation method). I close the issue :-)

**Closed as completed by dimitri-justeau** 2022-03-28 00:41 UTC
Labels: question

**Comment by jeffreyhanson** [comment] 2022-03-28 00:54
Brilliant - thanks!
